services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    hostname: n8n
    restart: always 
    ports:
      - "5678:5678"
    environment:
      # Dirección pública (ajústala según tu dominio o IP)
      N8N_HOST: n8n.pabpereza.dev
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://n8n.pabpereza.dev
      # Zona horaria
      GENERIC_TIMEZONE: Europe/Madrid
      TZ: Europe/Madrid
    volumes:
      - n8n:/home/node/.n8n
    networks:
      - npm_web
volumes:
  n8n:
networks:
  npm_web:
    external: true
